/**
 * Tricity location synonym / expansion graph.
 * Every locality expands into nearby corridors, highways, and micro-markets.
 */

import type { PlaceNode } from "./types";

export const PLACE_GRAPH: PlaceNode[] = [
  // ── Kharar belt ──────────────────────────────────────────────
  {
    id: "kharar",
    displayName: "Kharar",
    kind: "city",
    aliases: ["kharar", "kharad", "greater kharar"],
    nearby: [
      "Kurali",
      "Kurali Highway",
      "NH-21",
      "Chandigarh Highway",
      "Sunny Enclave",
      "Greater Mohali",
      "Landran Road",
      "New Chandigarh Belt",
      "TDI City",
      "Sector 123",
      "Sector 125",
    ],
    parentCity: "Mohali",
    lat: 30.7497,
    lng: 76.6469,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 3.0,
  },
  {
    id: "kurali",
    displayName: "Kurali",
    kind: "locality",
    aliases: ["kurali", "kurali town"],
    nearby: [
      "Kharar",
      "Kurali Highway",
      "NH-21",
      "Chandigarh Highway",
      "New Chandigarh",
      "Morinda",
    ],
    parentCity: "Mohali",
    lat: 30.834,
    lng: 76.58,
    surfaces: ["map", "forms", "filters", "admin", "ai", "explore"],
    mapRadiusKm: 2.6,
  },
  {
    id: "kurali-highway",
    displayName: "Kurali Highway",
    kind: "highway",
    aliases: [
      "kurali highway",
      "kurali-chandigarh highway",
      "kurali chandigarh highway",
      "kurali–chandigarh highway",
      "kurali - chandigarh highway",
    ],
    nearby: ["Kharar", "Kurali", "NH-21", "Chandigarh Highway", "New Chandigarh Belt"],
    parentCity: "Mohali",
    lat: 30.79,
    lng: 76.61,
  },
  {
    id: "nh-21",
    displayName: "NH-21",
    kind: "highway",
    aliases: ["nh-21", "nh21", "nh 21", "national highway 21", "nh-21 highway"],
    nearby: ["Kharar", "Kurali", "Kurali Highway", "Chandigarh Highway", "Ropar Road"],
    parentCity: "Mohali",
    lat: 30.78,
    lng: 76.62,
  },
  {
    id: "chandigarh-highway",
    displayName: "Chandigarh Highway",
    kind: "highway",
    aliases: [
      "chandigarh highway",
      "chd highway",
      "chandigarh road",
      "kharar chandigarh highway",
    ],
    nearby: ["Kharar", "Kurali Highway", "NH-21", "Sunny Enclave", "New Chandigarh Belt"],
    parentCity: "Mohali",
    lat: 30.76,
    lng: 76.65,
  },
  {
    id: "sunny-enclave",
    displayName: "Sunny Enclave",
    kind: "micromarket",
    aliases: ["sunny enclave", "sunny enclave kharar", "sunny enclave mohali"],
    nearby: ["Kharar", "Chandigarh Highway", "Greater Mohali", "Sector 125"],
    parentCity: "Mohali",
    lat: 30.755,
    lng: 76.66,
  },
  {
    id: "greater-mohali",
    displayName: "Greater Mohali",
    kind: "district",
    aliases: ["greater mohali", "gmada", "greater mohali area"],
    nearby: ["Kharar", "Mohali", "New Chandigarh", "Airport Road", "Landran"],
    parentCity: "Mohali",
    lat: 30.72,
    lng: 76.7,
  },
  {
    id: "landran-road",
    displayName: "Landran Road",
    kind: "corridor",
    aliases: ["landran road", "landran", "landran chowk"],
    nearby: ["Kharar", "Mohali", "Sector 115", "Sector 116", "IT City"],
    parentCity: "Mohali",
    lat: 30.69,
    lng: 76.66,
    surfaces: ["forms", "filters", "admin", "ai", "preferred"],
    suggestPriority: 70,
  },
  {
    id: "new-chandigarh-belt",
    displayName: "New Chandigarh Belt",
    kind: "corridor",
    aliases: [
      "new chandigarh belt",
      "new chandigarh",
      "mullanpur",
      "mullanpur garibdass",
      "eco city",
      "medi city",
    ],
    nearby: ["Kharar", "Kurali", "NH-21", "Chandigarh Highway", "Omaxe New Chandigarh"],
    parentCity: "New Chandigarh",
    lat: 30.82,
    lng: 76.7,
  },
  {
    id: "tdi-city",
    displayName: "TDI City",
    kind: "micromarket",
    aliases: ["tdi city", "tdi", "tdi sector"],
    nearby: ["Kharar", "New Chandigarh", "Sector 110", "Sector 117"],
    parentCity: "Mohali",
    lat: 30.77,
    lng: 76.69,
  },

  // ── Mohali ───────────────────────────────────────────────────
  {
    id: "mohali",
    displayName: "Mohali",
    kind: "city",
    aliases: ["mohali", "sas nagar", "s.a.s. nagar", "sasnagar", "sahibzada ajit singh nagar"],
    nearby: [
      "Sector 66",
      "Sector 67",
      "Sector 68",
      "Sector 69",
      "Sector 70",
      "Sector 71",
      "Sector 74",
      "Sector 75",
      "Sector 76",
      "Sector 77",
      "Sector 78",
      "Sector 79",
      "Sector 80",
      "Sector 82",
      "Sector 85",
      "Sector 88",
      "Sector 89",
      "Airport Road",
      "IT City",
      "JLPL",
      "Aerocity",
      "Wave Estate",
      "Sector Road",
      "Kharar",
      "Landran",
    ],
    parentCity: "Mohali",
    lat: 30.7046,
    lng: 76.7179,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 3.8,
  },
  {
    id: "airport-road",
    displayName: "Airport Road",
    kind: "corridor",
    aliases: ["airport road", "airport rd", "mohali airport road", "chd airport road"],
    nearby: ["Aerocity", "IT City", "JLPL", "Mohali", "Wave Estate", "PR7"],
    parentCity: "Mohali",
    lat: 30.68,
    lng: 76.76,
    surfaces: ["map", "filters", "ai", "explore"],
    mapRadiusKm: 2.0,
    suggestPriority: 75,
  },
  {
    id: "it-city",
    displayName: "IT City",
    kind: "micromarket",
    aliases: ["it city", "it city mohali", "infotech city"],
    nearby: ["Airport Road", "Aerocity", "JLPL", "Sector 82", "Sector 83", "Mohali"],
    parentCity: "Mohali",
    lat: 30.675,
    lng: 76.745,
    surfaces: ["forms", "filters", "admin", "preferred", "ai", "explore"],
    suggestPriority: 85,
  },
  {
    id: "jlpl",
    displayName: "JLPL",
    kind: "micromarket",
    aliases: ["jlpl", "jlpl industrial area", "j.l.p.l"],
    nearby: ["IT City", "Airport Road", "Aerocity", "Sector 82", "Mohali"],
    parentCity: "Mohali",
    lat: 30.67,
    lng: 76.74,
  },
  {
    id: "aerocity",
    displayName: "Aerocity",
    kind: "micromarket",
    aliases: ["aerocity", "aero city", "aerocity mohali", "aero-city"],
    nearby: ["Airport Road", "IT City", "JLPL", "PR7", "Wave Estate", "Mohali", "Zirakpur"],
    parentCity: "Mohali",
    lat: 30.665,
    lng: 76.785,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 2.2,
    suggestPriority: 90,
  },
  {
    id: "wave-estate",
    displayName: "Wave Estate",
    kind: "micromarket",
    aliases: ["wave estate", "wave", "wave city"],
    nearby: ["Aerocity", "Airport Road", "Sector 85", "Mohali"],
    parentCity: "Mohali",
    lat: 30.69,
    lng: 76.75,
  },
  {
    id: "sector-road",
    displayName: "Sector Road",
    kind: "corridor",
    aliases: ["sector road", "sector rd"],
    nearby: ["Mohali", "Sector 66", "Sector 67", "Sector 70"],
    parentCity: "Mohali",
    lat: 30.7,
    lng: 76.72,
  },

  // ── Zirakpur ─────────────────────────────────────────────────
  {
    id: "zirakpur",
    displayName: "Zirakpur",
    kind: "city",
    aliases: ["zirakpur", "zeerakpur", "zirakpur chandigarh"],
    nearby: [
      "VIP Road",
      "Patiala Road",
      "PR7",
      "Peer Muchalla",
      "Dhakoli",
      "Gazipur",
      "Baltana",
      "Aerocity",
    ],
    parentCity: "Zirakpur",
    lat: 30.6425,
    lng: 76.8173,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 3.2,
  },
  {
    id: "vip-road",
    displayName: "VIP Road",
    kind: "highway",
    aliases: ["vip road", "vip rd", "zirakpur vip road"],
    nearby: ["Zirakpur", "Patiala Road", "Peer Muchalla", "Gazipur"],
    parentCity: "Zirakpur",
    lat: 30.645,
    lng: 76.82,
  },
  {
    id: "patiala-road",
    displayName: "Patiala Road",
    kind: "highway",
    aliases: ["patiala road", "patiala rd", "nh-7", "nh7"],
    nearby: ["Zirakpur", "VIP Road", "Dhakoli", "Banur"],
    parentCity: "Zirakpur",
    lat: 30.63,
    lng: 76.83,
  },
  {
    id: "pr7",
    displayName: "PR7",
    kind: "corridor",
    aliases: ["pr7", "pr-7", "pr 7", "pr7 road"],
    nearby: ["Aerocity", "Zirakpur", "Airport Road", "Gazipur"],
    parentCity: "Mohali",
    lat: 30.655,
    lng: 76.8,
    surfaces: ["map", "filters", "ai", "explore"],
    mapRadiusKm: 2.0,
    suggestPriority: 88,
  },
  {
    id: "peer-muchalla",
    displayName: "Peer Muchalla",
    kind: "micromarket",
    aliases: [
      "peer muchalla",
      "peermuchalla",
      "peer muchala",
      "peer muchalla zirakpur",
      "pir muchalla",
    ],
    nearby: ["Zirakpur", "VIP Road", "Dhakoli", "Gazipur", "Baltana"],
    parentCity: "Zirakpur",
    // East of Zirakpur / VIP Road — near Panchkula Sector 5 belt (not city centre)
    lat: 30.6725,
    lng: 76.8728,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 1.8,
    suggestPriority: 86,
  },
  {
    id: "dhakoli",
    displayName: "Dhakoli",
    kind: "micromarket",
    aliases: [
      "dhakoli",
      "dhakkoli",
      "dhakoli zirakpur",
      "dhakoli chandigarh",
    ],
    nearby: ["Zirakpur", "Patiala Road", "Peer Muchalla", "Baltana", "Gazipur"],
    parentCity: "Zirakpur",
    // Wikipedia / field centroid — was incorrectly near Panchkula (~30.696)
    lat: 30.6553,
    lng: 76.8426,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 1.8,
    suggestPriority: 85,
  },
  {
    id: "baltana",
    displayName: "Baltana",
    kind: "locality",
    aliases: ["baltana", "baltana zirakpur"],
    nearby: ["Zirakpur", "Dhakoli", "Patiala Road"],
    parentCity: "Zirakpur",
    lat: 30.628,
    lng: 76.838,
    surfaces: ["forms", "filters", "admin"],
  },

  // ── Core cities ──────────────────────────────────────────────
  {
    id: "chandigarh",
    displayName: "Chandigarh",
    kind: "city",
    aliases: ["chandigarh", "chd", "chandigarh city", "ut chandigarh"],
    nearby: ["Mohali", "Panchkula", "Zirakpur", "Manimajra", "Industrial Area"],
    parentCity: "Chandigarh",
    lat: 30.7333,
    lng: 76.7794,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 4.2,
  },
  {
    id: "panchkula",
    displayName: "Panchkula",
    kind: "city",
    aliases: ["panchkula", "pkul", "pkl", "panchkula haryana"],
    nearby: [
      "Chandigarh",
      "Zirakpur",
      "Sector 20",
      "Sector 21",
      "Sector 8",
      "Sector 7",
      "Sector 5",
      "Sector 4",
      "Panchkula Extension 1",
      "Panchkula Extension 2",
      "Amravati Enclave",
      "Pinjore",
      "Kalka",
    ],
    parentCity: "Panchkula",
    lat: 30.6942,
    lng: 76.8606,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 3.4,
    suggestPriority: 45,
  },

  // ── Panchkula sectors & micro-markets ────────────────────────
  {
    id: "panchkula-sector-20",
    displayName: "Sector 20",
    kind: "sector",
    aliases: [
      "sector 20",
      "sec 20",
      "sec. 20",
      "s20",
      "sector-20",
      "sector 20 panchkula",
      "panchkula sector 20",
      "pkl sector 20",
    ],
    nearby: [
      "Panchkula",
      "Sector 21",
      "Sector 8",
      "Panchkula Extension 1",
    ],
    parentCity: "Panchkula",
    lat: 30.6985,
    lng: 76.872,
  },
  {
    id: "panchkula-sector-21",
    displayName: "Sector 21",
    kind: "sector",
    aliases: [
      "sector 21",
      "sec 21",
      "sec. 21",
      "s21",
      "sector-21",
      "sector 21 panchkula",
      "panchkula sector 21",
      "pkl sector 21",
    ],
    nearby: [
      "Panchkula",
      "Sector 20",
      "Sector 8",
      "Panchkula Extension 1",
    ],
    parentCity: "Panchkula",
    lat: 30.702,
    lng: 76.868,
  },
  {
    id: "panchkula-sector-8",
    displayName: "Sector 8",
    kind: "sector",
    aliases: [
      "sector 8",
      "sec 8",
      "sec. 8",
      "s8",
      "sector-8",
      "sector 8 panchkula",
      "panchkula sector 8",
      "pkl sector 8",
    ],
    nearby: ["Panchkula", "Sector 7", "Sector 5", "Sector 20"],
    parentCity: "Panchkula",
    lat: 30.706,
    lng: 76.855,
  },
  {
    id: "panchkula-sector-7",
    displayName: "Sector 7",
    kind: "sector",
    aliases: [
      "sector 7",
      "sec 7",
      "sec. 7",
      "s7",
      "sector-7",
      "sector 7 panchkula",
      "panchkula sector 7",
      "pkl sector 7",
    ],
    nearby: ["Panchkula", "Sector 8", "Sector 5", "Sector 4"],
    parentCity: "Panchkula",
    lat: 30.71,
    lng: 76.85,
  },
  {
    id: "panchkula-sector-5",
    displayName: "Sector 5",
    kind: "sector",
    aliases: [
      "sector 5",
      "sec 5",
      "sec. 5",
      "s5",
      "sector-5",
      "sector 5 panchkula",
      "panchkula sector 5",
      "pkl sector 5",
    ],
    nearby: ["Panchkula", "Sector 4", "Sector 7", "Sector 8"],
    parentCity: "Panchkula",
    lat: 30.714,
    lng: 76.846,
  },
  {
    id: "panchkula-sector-4",
    displayName: "Sector 4",
    kind: "sector",
    aliases: [
      "sector 4",
      "sec 4",
      "sec. 4",
      "s4",
      "sector-4",
      "sector 4 panchkula",
      "panchkula sector 4",
      "pkl sector 4",
    ],
    nearby: ["Panchkula", "Sector 5", "Sector 7"],
    parentCity: "Panchkula",
    lat: 30.718,
    lng: 76.842,
  },
  {
    id: "panchkula-extension-1",
    displayName: "Panchkula Extension 1",
    kind: "micromarket",
    aliases: [
      "panchkula extension 1",
      "panchkula extension-1",
      "panchkula ext 1",
      "panchkula ext. 1",
      "pkl extension 1",
      "pkl ext 1",
      "pkl extension-1",
      "pkul extension 1",
      "panchkula ext1",
      "extension 1 panchkula",
      "panchkula extensions 1",
      // Bare "Panchkula Extension" (no number) — numbered aliases still win when present
      "panchkula extension",
      "pkl extension",
      "pkul extension",
    ],
    nearby: [
      "Panchkula",
      "Panchkula Extension 2",
      "Amravati Enclave",
      "Sector 20",
      "Sector 21",
      "Zirakpur",
    ],
    parentCity: "Panchkula",
    lat: 30.668,
    lng: 76.872,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 1.8,
    suggestPriority: 95,
  },
  {
    id: "panchkula-extension-2",
    displayName: "Panchkula Extension 2",
    kind: "micromarket",
    aliases: [
      "panchkula extension 2",
      "panchkula extension-2",
      "panchkula ext 2",
      "panchkula ext. 2",
      "pkl extension 2",
      "pkl ext 2",
      "pkl extension-2",
      "pkul extension 2",
      "panchkula ext2",
      "extension 2 panchkula",
      "panchkula extensions 2",
    ],
    nearby: [
      "Panchkula",
      "Panchkula Extension 1",
      "Amravati Enclave",
      "Sector 20",
      "Zirakpur",
    ],
    parentCity: "Panchkula",
    lat: 30.658,
    lng: 76.885,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 1.8,
    suggestPriority: 95,
  },
  {
    id: "amravati-enclave",
    displayName: "Amravati Enclave",
    kind: "micromarket",
    aliases: [
      "amravati enclave",
      "amravati",
      "amravati panchkula",
      "amravati enclave panchkula",
      "amrawati enclave",
      "amrawati",
      "amaravati enclave",
      "amravati colony",
    ],
    nearby: [
      "Panchkula",
      "Panchkula Extension 1",
      "Panchkula Extension 2",
      "Sector 20",
      "Zirakpur",
    ],
    parentCity: "Panchkula",
    lat: 30.662,
    lng: 76.878,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 1.5,
    suggestPriority: 96,
  },

  {
    id: "new-chandigarh",
    displayName: "New Chandigarh",
    kind: "city",
    aliases: ["new chandigarh", "new chd"],
    nearby: ["New Chandigarh Belt", "Kharar", "Kurali", "Mullanpur", "Eco City"],
    parentCity: "New Chandigarh",
    lat: 30.82,
    lng: 76.7,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 3.6,
  },
  {
    id: "derabassi",
    displayName: "Derabassi",
    kind: "city",
    aliases: ["derabassi", "dera bassi", "derabasi"],
    nearby: ["Zirakpur", "Airport Road", "Banur", "Barwala"],
    parentCity: "Derabassi",
    lat: 30.585,
    lng: 76.845,
    surfaces: [
      "map",
      "forms",
      "filters",
      "preferred",
      "admin",
      "connect",
      "ai",
      "explore",
    ],
    mapRadiusKm: 2.8,
  },
  {
    id: "banur",
    displayName: "Banur",
    kind: "city",
    aliases: ["banur", "banur town"],
    nearby: ["Derabassi", "Patiala Road", "Rajpura"],
    parentCity: "Banur",
    lat: 30.555,
    lng: 76.72,
    surfaces: ["forms", "filters", "admin", "ai", "explore"],
  },
];

/** Mohali sectors 66–89 as individual searchable nodes. */
const MOHALI_SECTORS = [
  66, 67, 68, 69, 70, 71, 74, 75, 76, 77, 78, 79, 80, 82, 85, 88, 89, 115, 116,
  117, 118, 123, 125,
];

for (const n of MOHALI_SECTORS) {
  PLACE_GRAPH.push({
    id: `sector-${n}`,
    displayName: `Sector ${n}`,
    kind: "sector",
    aliases: [`sector ${n}`, `sec ${n}`, `sec. ${n}`, `s${n}`, `sector-${n}`],
    nearby: ["Mohali", "Airport Road", "IT City"],
    parentCity: "Mohali",
    lat: 30.7 + (n - 70) * 0.002,
    lng: 76.72 + (n - 70) * 0.002,
  });
}

const byId = new Map(PLACE_GRAPH.map((p) => [p.id, p]));
const byAlias = new Map<string, PlaceNode>();

function normAlias(s: string): string {
  return s
    .toLowerCase()
    .replace(/[–—−]/g, "-")
    .replace(/[^a-z0-9\s.-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

for (const place of PLACE_GRAPH) {
  byAlias.set(normAlias(place.displayName), place);
  for (const a of place.aliases) {
    byAlias.set(normAlias(a), place);
  }
}

export function normalizePlaceToken(s: string): string {
  return normAlias(s);
}

export function getPlaceById(id: string): PlaceNode | undefined {
  return byId.get(id);
}

export function getPlaceByAlias(token: string): PlaceNode | undefined {
  return byAlias.get(normAlias(token));
}

/** All alias keys sorted longest-first for greedy query scanning. */
export const ALL_ALIAS_KEYS: string[] = [...byAlias.keys()].sort(
  (a, b) => b.length - a.length,
);

export function resolveNearbyNodes(place: PlaceNode): PlaceNode[] {
  const out: PlaceNode[] = [];
  const seen = new Set<string>([place.id]);
  for (const name of place.nearby) {
    const node = getPlaceByAlias(name) ?? getPlaceById(normalizePlaceToken(name));
    if (node && !seen.has(node.id)) {
      seen.add(node.id);
      out.push(node);
    }
  }
  return out;
}
