import type { ActivityType, LeadStatus } from "./types";

export const LEAD_STATUS_LABELS: Record<LeadStatus, string> = {
  new: "New",
  ai_qualified: "AI Qualified",
  interested: "Interested",
  property_suggested: "Property Suggested",
  property_saved: "Property Saved",
  inquiry_sent: "Inquiry Sent",
  visit_scheduled: "Visit Scheduled",
  visited: "Visited",
  negotiation: "Negotiation",
  booked: "Booked",
  completed: "Completed",
  lost: "Lost",
};

export const LEAD_STATUS_ORDER: LeadStatus[] = [
  "new",
  "ai_qualified",
  "interested",
  "property_suggested",
  "property_saved",
  "inquiry_sent",
  "visit_scheduled",
  "visited",
  "negotiation",
  "booked",
  "completed",
  "lost",
];

export const ACTIVITY_STATUS_MAP: Partial<Record<ActivityType, LeadStatus>> = {
  buyer_registered: "new",
  buyer_first_login: "new",
  ai_chat_started: "ai_qualified",
  ai_chat_message: "ai_qualified",
  property_viewed: "interested",
  property_saved: "property_saved",
  property_compared: "interested",
  contact_requested: "interested",
  inquiry_sent: "inquiry_sent",
  visit_requested: "visit_scheduled",
  site_visit_booked: "visit_scheduled",
  site_visit_accepted: "visit_scheduled",
  site_visit_rescheduled: "visit_scheduled",
  site_visit_completed: "visited",
  visit_feedback_submitted: "visited",
  visit_notes_saved: "visit_scheduled",
  partner_call: "interested",
  partner_whatsapp: "interested",
  partner_email: "interested",
  follow_up_scheduled: "interested",
  negotiation_started: "negotiation",
  deal_booked: "booked",
  deal_closed: "completed",
  deal_lost: "lost",
};

export const PIPELINE_STAGES: Array<{ status: LeadStatus; label: string; group: string }> = [
  { status: "new", label: "New", group: "Lead" },
  { status: "ai_qualified", label: "Attempted Contact", group: "Lead" },
  { status: "interested", label: "Connected", group: "Lead" },
  { status: "property_saved", label: "Qualified", group: "Lead" },
  { status: "inquiry_sent", label: "Qualified", group: "Lead" },
  { status: "visit_scheduled", label: "Visit Requested", group: "Visit" },
  { status: "visited", label: "Visit Completed", group: "Visit" },
  { status: "negotiation", label: "Negotiation", group: "Deal" },
  { status: "booked", label: "Token / Booked", group: "Deal" },
  { status: "completed", label: "Closed Won", group: "Deal" },
  { status: "lost", label: "Closed Lost", group: "Deal" },
];

export const ACTIVITY_ICONS: Record<ActivityType, string> = {
  buyer_registered: "👤",
  buyer_first_login: "🔑",
  ai_chat_started: "💬",
  ai_chat_message: "🤖",
  property_viewed: "👀",
  property_saved: "❤️",
  property_unsaved: "💔",
  property_compared: "⚖️",
  contact_requested: "📞",
  inquiry_sent: "📩",
  visit_requested: "📅",
  site_visit_booked: "📅",
  site_visit_accepted: "✅",
  site_visit_rejected: "🚫",
  site_visit_rescheduled: "🔄",
  site_visit_completed: "✅",
  site_visit_cancelled: "❌",
  visit_checklist_generated: "📋",
  visit_feedback_submitted: "📝",
  visit_notes_saved: "📓",
  negotiation_started: "🤝",
  deal_booked: "🏠",
  deal_closed: "🎉",
  deal_lost: "😔",
  lead_assigned: "🔗",
  lead_reassigned: "🔄",
  status_changed: "📊",
  partner_call: "📞",
  partner_whatsapp: "💬",
  partner_email: "📧",
  follow_up_scheduled: "📅",
  follow_up_completed: "✅",
  document_uploaded: "📄",
  reminder_sent: "🔔",
};
