import type { ActivityType, LeadStatus } from "./types";

export const LEAD_STATUS_LABELS: Record<LeadStatus, string> = {
  new: "New",
  ai_qualified: "AI Qualified",
  interested: "Interested",
  property_suggested: "Property Suggested",
  property_saved: "Property Saved",
  inquiry_sent: "Inquiry Sent",
  visit_scheduled: "Visit Scheduled",
  visited: "Visited",
  negotiation: "Negotiation",
  booked: "Booked",
  completed: "Completed",
  lost: "Lost",
};

export const LEAD_STATUS_ORDER: LeadStatus[] = [
  "new",
  "ai_qualified",
  "interested",
  "property_suggested",
  "property_saved",
  "inquiry_sent",
  "visit_scheduled",
  "visited",
  "negotiation",
  "booked",
  "completed",
  "lost",
];

export const ACTIVITY_STATUS_MAP: Partial<Record<ActivityType, LeadStatus>> = {
  buyer_registered: "new",
  buyer_first_login: "new",
  ai_chat_started: "ai_qualified",
  ai_chat_message: "ai_qualified",
  property_viewed: "interested",
  property_saved: "property_saved",
  contact_requested: "interested",
  inquiry_sent: "inquiry_sent",
  visit_requested: "visit_scheduled",
  site_visit_booked: "visit_scheduled",
  site_visit_accepted: "visit_scheduled",
  site_visit_rescheduled: "visit_scheduled",
  site_visit_completed: "visited",
  visit_feedback_submitted: "visited",
  negotiation_started: "negotiation",
  deal_booked: "booked",
  deal_closed: "completed",
  deal_lost: "lost",
};

export const ACTIVITY_ICONS: Record<ActivityType, string> = {
  buyer_registered: "👤",
  buyer_first_login: "🔑",
  ai_chat_started: "💬",
  ai_chat_message: "🤖",
  property_viewed: "👀",
  property_saved: "❤️",
  property_unsaved: "💔",
  contact_requested: "📞",
  inquiry_sent: "📩",
  visit_requested: "📅",
  site_visit_booked: "📅",
  site_visit_accepted: "✅",
  site_visit_rejected: "🚫",
  site_visit_rescheduled: "🔄",
  site_visit_completed: "✅",
  site_visit_cancelled: "❌",
  visit_checklist_generated: "📋",
  visit_feedback_submitted: "📝",
  negotiation_started: "🤝",
  deal_booked: "🏠",
  deal_closed: "🎉",
  deal_lost: "😔",
  lead_assigned: "🔗",
  lead_reassigned: "🔄",
  status_changed: "📊",
};
