/** Premium Ask loading copy — tips, facts, thinking lines, did-you-knows. */

export const PROPERTY_INTELLIGENCE_TIPS: string[] = [
  "Never buy only because of launch price.",
  "Corner plots usually command higher resale.",
  "Always compare at least three builders.",
  "Verify RERA before paying booking amount.",
  "Visit projects during office hours for a realistic view.",
  "Future roads matter more than current roads.",
  "Metro announcements often move prices before construction starts.",
  "Rental demand is highest near IT hubs and campuses.",
  "Builder delivery history matters more than advertisements.",
  "Maintenance charges affect your long-term ownership cost.",
  "Check waterlogging history before shortlisting a locality.",
  "A lower floor can mean better resale liquidity in some towers.",
  "Ask for the payment schedule in writing — never rely on verbal promises.",
  "Possession timelines slip; build a 6–12 month buffer into plans.",
  "Compare price per sq ft on carpet area, not super area alone.",
  "Club membership and parking often hide in the fine print.",
  "North- and east-facing units can carry a location premium.",
  "Prefer projects with clear title and society registration path.",
  "Soft launches can offer better entry pricing than grand launches.",
  "Walk the approach road at peak hour — connectivity is lived, not marketed.",
  "Check distance to the nearest hospital and school yourself.",
  "Resale inventory can beat new launches on immediate livability.",
  "Ask how many towers are already delivered in the same project.",
  "Plot size efficiency matters — odd shapes reduce usable area.",
  "Builder brand alone is not due diligence.",
  "Look at unsold inventory — it signals pricing pressure.",
  "Verify floor plan against the sanctioned drawing.",
  "Balcony and utility areas inflate ‘super area’ quotes.",
  "Prefer localities with multiple exit roads for daily commute.",
  "Noise from highways and railways compounds over years.",
  "Check whether the project is in a flood-prone micro-pocket.",
  "Rental yield and appreciation rarely peak in the same asset.",
  "End-use buyers and investors should use different shortlists.",
  "Ask for past delay history across the builder’s other projects.",
  "A ready-to-move home reduces EMI + rent double load.",
  "Compare three nearby projects on the same configuration.",
  "Don’t ignore society bylaws if you plan to rent later.",
  "Power backup cost is a real monthly expense.",
  "Corner shops and main-road facing plots price differently.",
  "Check proposed flyovers and underpasses on local master plans.",
  "Booking amount is usually ~5% — confirm before you transfer funds.",
  "Prefer banks that already finance the specific project.",
  "Registry charges and stamp duty are part of true cost.",
  "A gated community is not the same as a managed society.",
  "Ask who maintains common areas after possession.",
  "View the sample flat and an actual under-construction floor.",
  "Prefer transparent escalation clauses in construction-linked plans.",
  "Locality brand fades if micro-location access is weak.",
  "Check cellphone coverage and water pressure on site visits.",
  "Afternoon sun and west-facing glare affect daily comfort.",
  "Don’t skip a lawyer for agreement review on large tickets.",
  "Compare circle rates with asking price as a sanity check.",
  "Multiple parking slots matter more than brochure amenities.",
  "A second bathroom can improve rental absorption for 3 BHKs.",
  "Study evening footfall before buying a retail-facing unit.",
  "Prefer projects with completed external development nearby.",
  "Ask whether the road in front is private or municipal.",
  "Resale negotiation room is usually higher than new-launch.",
  "Track how many units sold in the last 90 days.",
  "Avoid paying cash components outside the agreement.",
  "Check if the project has a valid environmental clearance trail.",
  "Builder escrow and RERA account discipline protect your money.",
  "A longer lease tenure often beats a slightly lower rent.",
  "IT corridor spillover can lift secondary localities later.",
  "Plot townships need infra delivery, not just entrance arches.",
  "Verify carpet area with a tape on ready inventory.",
  "Ask for OC / CC status in writing for ready homes.",
  "Neighbourhood parks and walking paths drive daily satisfaction.",
  "Prefer projects where the builder lives nearby — skin in the game.",
  "Seasonal fog and air quality differ sharply across Tricity pockets.",
  "A wider approach road supports both daily life and resale.",
  "Don’t confuse ‘launch price’ with all-in cost to move in.",
  "Check lift ratio and lobby quality — they age with the building.",
  "For investment, exit liquidity matters as much as entry price.",
  "Compare stamp duty implications across family ownership structures.",
  "A home near a university can support student rental demand.",
  "Industrial belts may hurt residential livability even if prices look low.",
  "Ask how many floors the tower will finally have.",
  "Prefer documented green cover over brochure renderings.",
  "Weekend site visits miss weekday traffic reality.",
  "Check rainwater harvesting and sewage handling on site.",
  "A project’s first phase often has better pricing than later phases.",
  "Builder ‘assured returns’ schemes need extra legal scrutiny.",
  "Prefer clear demarcation of common vs private areas.",
  "Study nearby vacant land — future supply can cap upside.",
  "School proximity helps family demand; nightlife helps rental mix.",
  "Always photograph the site and approach road during visits.",
  "Ask for the latest demand letter format before booking.",
  "Prefer units with natural cross-ventilation.",
  "A longer possession wait needs stronger price discipline.",
  "Check whether commercial shops face the residential towers.",
  "Municipal water vs tanker dependency changes monthly cost.",
  "Don’t skip comparing two banks’ home-loan offers.",
  "Resale with clear chain of documents closes faster.",
  "Look at tower orientation relative to afternoon heat.",
  "A locality with mixed use can support convenience and noise.",
  "Ask what is included in the quoted maintenance deposit.",
  "Prefer sellers who share previous sale comps for the same tower.",
  "Infrastructure news is priced in quickly — act on verified timelines.",
  "Your EMI comfort should assume rate rises, not best-case rates.",
  "The best deal is the one you can exit without panic.",
  "Walk away if urgency tactics replace transparent answers.",
];

export const THINKING_STATUS_MESSAGES: string[] = [
  "Searching live properties…",
  "Checking builder credibility…",
  "Calculating investment score…",
  "Reading RERA information…",
  "Comparing nearby projects…",
  "Analysing price trends…",
  "Estimating appreciation…",
  "Looking for better alternatives…",
  "I'm comparing projects around your preferred location.",
  "Checking builder credibility against delivery history…",
  "Looking beyond the advertised price…",
  "Finding better investment options nearby…",
  "Reviewing nearby infrastructure plans…",
  "Comparing appreciation trends across micro-markets…",
  "Checking nearby schools and daily conveniences…",
  "Matching listings to your budget comfort zone…",
  "Reading recent market movement in this corridor…",
  "Analyzing rental demand near employment hubs…",
  "Comparing nearby projects on value, not hype…",
  "Calculating affordability with realistic ownership costs…",
  "Finding hidden opportunities in secondary localities…",
  "Matching your lifestyle to the right micro-location…",
  "Checking future road and metro connectivity…",
  "Reviewing builder reputation signals…",
  "Looking for stronger carpet-area efficiency…",
  "Comparing possession readiness vs under-construction risk…",
  "Scanning live inventory for configuration fit…",
  "Evaluating long-term maintenance burden…",
  "Checking whether price aligns with local comps…",
  "Reviewing locality livability factors…",
  "Comparing plot vs apartment trade-offs for your goal…",
  "Looking at exit liquidity for similar inventory…",
  "Checking RERA and compliance cues where available…",
  "Weighing end-use comfort against investment upside…",
  "Reviewing approach roads and peak-hour access…",
  "Comparing phase-wise pricing within the same project…",
  "Finding options with clearer documentation trails…",
  "Checking distance to hospitals, schools, and daily needs…",
  "Analyzing whether this pocket is supply-heavy…",
  "Looking for better negotiation room on resale stock…",
  "Comparing soft-launch value against launched inventory…",
  "Reviewing amenities that actually affect daily life…",
  "Checking orientation, light, and practical floor preference…",
  "Matching your timeline to ready vs under-construction stock…",
  "Looking for corridors with stronger rental absorption…",
  "Comparing ticket size against typical Tricity demand…",
  "Reviewing risk flags before I recommend anything…",
  "Narrowing to options I’d shortlist for a site visit…",
  "Cross-checking locality stories against live listings…",
  "Balancing commute, community, and capital growth…",
  "Preparing a clear recommendation — not a random shortlist…",
  "Double-checking that the budget still fits after extras…",
];

/** Featured rotating research cards shown while AI thinks (3–4s cadence). */
export const THINKING_RESEARCH_CARDS: { title: string; detail: string }[] = [
  { title: "Searching live properties…", detail: "Scanning AreaIQ inventory that matches your brief." },
  { title: "Checking builder credibility…", detail: "Reviewing delivery history and reputation signals." },
  { title: "Calculating investment score…", detail: "Weighing appreciation, yield, and exit liquidity." },
  { title: "Reading RERA information…", detail: "Looking for registration and compliance cues." },
  { title: "Comparing nearby projects…", detail: "Benchmarking value against local comps." },
  { title: "Analysing price trends…", detail: "Reading recent movement in this corridor." },
  { title: "Estimating appreciation…", detail: "Modelling mid-term upside with infrastructure context." },
  { title: "Looking for better alternatives…", detail: "Finding stronger options you may have missed." },
];

export const DID_YOU_KNOW: string[] = [
  "Projects within 1 km of metro stations often appreciate faster once operations begin.",
  "Plots can outperform apartments in long-term appreciation when infrastructure lands on time.",
  "Carpet area — not super area — is the fairest way to compare two homes.",
  "A 6–12 month possession buffer is common even on ‘on-time’ projects.",
  "Booking amounts are often around 5% of the ticket size — confirm before you transfer.",
  "North-facing plots frequently carry a premium in many North Indian markets.",
  "RERA registration is a baseline safeguard, not a guarantee of on-time delivery.",
  "Soft launches sometimes offer better entry pricing than public grand launches.",
  "Corner units and park-facing homes can command higher resale demand.",
  "Maintenance deposits and club charges can change your true monthly cost.",
  "IT corridor expansion has historically lifted secondary localities before they feel ‘prime’.",
  "Ready-to-move inventory removes the EMI + rent double burden many buyers underestimate.",
  "Builder delay history across older projects is often more predictive than brochure claims.",
  "Liquidity matters: a slightly pricier unit in a liquid pocket can exit faster.",
  "Weekend site visits miss weekday traffic — visit once during office hours.",
  "Waterlogging risk is locality-specific; ask neighbours, not only sales teams.",
  "Home-loan eligibility and project bank approval are separate checks.",
  "Stamp duty and registration can add a meaningful percentage on top of agreement value.",
  "A wider approach road supports both livability and future resale.",
  "Unsold inventory in a tower can create negotiation room for serious buyers.",
  "End-use buyers and pure investors should rarely share the same shortlist.",
  "Metro and highway announcements move prices before steel is even visible.",
  "Sample flats are styled for emotion — inspect a real floor plate too.",
  "Society bylaws can restrict rentals, pets, or commercial use later.",
  "Power backup and water sourcing quietly decide monthly ownership comfort.",
];

export const REAL_ESTATE_FACTS: { title: string; body: string }[] = [
  { title: "Typical possession window", body: "Many under-construction homes target 24–36 months — plan a buffer." },
  { title: "Booking amount", body: "Often around 5% of the property value; always confirm in writing." },
  { title: "Facing premium", body: "North-facing plots and better-lit units often carry a price premium." },
  { title: "RERA protection", body: "RERA improves transparency on registration, escrow, and complaint paths." },
  { title: "Soft-launch pricing", body: "Early inventory can be priced sharper before marketing peaks." },
  { title: "Stamp duty reality", body: "Registration and stamp duty are part of true acquisition cost." },
  { title: "Carpet vs super area", body: "Price comparisons work best on carpet area efficiency." },
  { title: "Maintenance matters", body: "High amenities can mean higher monthly outgo after possession." },
  { title: "Loan pre-approval", body: "Get in-box loan comfort before you fall in love with a unit." },
  { title: "Resale liquidity", body: "Homes near employment hubs generally find tenants and buyers faster." },
  { title: "Delay buffer", body: "Build 6–12 months of flexibility into possession-linked plans." },
  { title: "Site visit timing", body: "Weekday peak-hour visits reveal commute truth better than Sundays." },
  { title: "Payment schedule", body: "Construction-linked plans should be transparent and milestone-based." },
  { title: "Hidden extras", body: "Parking, club, and floor rise can add meaningfully to the quote." },
  { title: "Documentation", body: "Clear title and sanctioned plans reduce closing friction." },
  { title: "Infrastructure lag", body: "Advertised roads can take years after project launch to feel complete." },
  { title: "Rental corridors", body: "Demand clusters near IT parks, hospitals, and universities." },
  { title: "Negotiation room", body: "Resale stock often has more flexibility than fixed new-launch slabs." },
  { title: "Tower maturity", body: "Delivered phases nearby are a useful signal of builder execution." },
  { title: "Orientation comfort", body: "West glare and heat can affect daily livability as much as view." },
  { title: "Society readiness", body: "OC/CC status changes how quickly you can move in or rent out." },
  { title: "Supply pressure", body: "Heavy nearby launches can cap near-term price upside." },
  { title: "Approach road", body: "Last-mile access quality often decides daily satisfaction." },
  { title: "Escrow discipline", body: "RERA account practices help keep buyer money tied to the project." },
  { title: "True EMI load", body: "Stress-test affordability for rate increases, not best-case EMIs." },
  { title: "Exit planning", body: "Buy with a realistic 5–7 year horizon for investment inventory." },
  { title: "Local comps", body: "Nearby closed deals beat brochure ‘starting prices’ for truth." },
  { title: "Water & power", body: "Municipal supply reliability varies sharply by micro-locality." },
  { title: "Parking demand", body: "Extra parking often improves both livability and resale." },
  { title: "Legal review", body: "Agreement review is cheap insurance on high-ticket purchases." },
  { title: "Phase pricing", body: "Later phases can price higher once a project looks ‘live’." },
  { title: "Amenity ROI", body: "Daily-use amenities beat rarely used luxury facilities." },
  { title: "Noise factors", body: "Highways and commercial edges can discount residential comfort." },
  { title: "Flood risk", body: "Ask about monsoon history — maps don’t tell the full story." },
  { title: "Tenant profile", body: "Family vs bachelor demand changes which configurations absorb rent." },
  { title: "Broker vs direct", body: "Transparency of terms matters more than who introduced the deal." },
  { title: "Circle rates", body: "Use circle rate as a floor check, not the only valuation tool." },
  { title: "Fit-out cost", body: "Bare-shell or semi-furnished handovers change move-in budgets." },
  { title: "Community mix", body: "Neighbourhood profile affects both lifestyle and rental quality." },
  { title: "Future supply", body: "Vacant land nearby can become competing inventory later." },
  { title: "Bank project list", body: "Preferred project status can simplify home-loan processing." },
  { title: "Possession clause", body: "Read delay penalty and force-majeure language carefully." },
  { title: "Sample vs reality", body: "Sample flats are aspirational; floor plates are contractual." },
  { title: "Corner premium", body: "Corner plots and end units often price and resell differently." },
  { title: "Metro effect", body: "Price reaction often starts at announcement, not inauguration." },
  { title: "Yield vs growth", body: "High rental yield and fast appreciation rarely peak together." },
  { title: "Document chain", body: "Resale closes faster with a clean ownership paper trail." },
  { title: "Walkability", body: "Daily errands without a car raise long-term livability scores." },
  { title: "Sales urgency", body: "Pressure tactics are a signal to slow down, not speed up." },
  { title: "Total cost of ownership", body: "Price + taxes + maintenance + commute time is the real number." },
  { title: "Advisory mindset", body: "Shortlist fewer, better options — then verify on the ground." },
  { title: "Tricity corridors", body: "Airport, IT, and highway belts shape where demand concentrates next." },
];

export type TimelineStepId =
  | "understand"
  | "search"
  | "compare"
  | "builder"
  | "investment"
  | "recommend";

export interface TimelineStepDef {
  id: TimelineStepId;
  activeLabel: string;
  doneLabel: string;
}

export const TIMELINE_STEPS: TimelineStepDef[] = [
  {
    id: "understand",
    activeLabel: "Understanding your requirement…",
    doneLabel: "Requirement understood",
  },
  {
    id: "search",
    activeLabel: "Searching live listings…",
    doneLabel: "Live listings reviewed",
  },
  {
    id: "compare",
    activeLabel: "Comparing nearby projects…",
    doneLabel: "Locality compared",
  },
  {
    id: "builder",
    activeLabel: "Checking builder profile…",
    doneLabel: "Builder signals checked",
  },
  {
    id: "investment",
    activeLabel: "Evaluating investment potential…",
    doneLabel: "Investment angles weighed",
  },
  {
    id: "recommend",
    activeLabel: "Preparing recommendation…",
    doneLabel: "Recommendation ready",
  },
];

/** Milliseconds between timeline step advances (range mid-point ~1.6s). */
export const TIMELINE_STEP_MS = 1600;
export const TIP_ROTATE_MS = 4000;
export const THINKING_ROTATE_MS = 3500;
export const THINKING_CARD_ROTATE_MS = 3500;
export const DID_YOU_KNOW_ROTATE_MS = 6000;
export const FACT_ROTATE_MS = 5500;
export const LONG_WAIT_MS = 5000;
export const ALMOST_DONE_MS = 10000;
