import { createSupabaseServiceClient } from "@/lib/supabase/service";
import { logConnectPartnerActivity } from "./service";
import type { ConnectPartnerActivityType } from "@/lib/supabase";

export interface PartnerEngagementInput {
  propertyId: string;
  buyerId: string;
  leadId?: string | null;
  siteVisitId?: string | null;
  actorId?: string | null;
  activityType?: ConnectPartnerActivityType;
  description?: string;
}

/**
 * Records a Connect-partner engagement generated by a buyer transaction on a
 * partner-assigned property.
 *
 * Ownership model: Property → Connect Partner → transaction. The partner id is
 * stamped on each transaction row (inquiries, site_visits, crm_lead_activities)
 * and on the partner-scoped CRM lead at insert time. This function ONLY writes
 * the partner activity timeline — it never assigns the buyer to a partner and
 * never overwrites ownership of previous transactions.
 */
export async function logPartnerEngagementFromProperty(
  input: PartnerEngagementInput,
): Promise<void> {
  const supabase = createSupabaseServiceClient();

  const { data: property, error } = await supabase
    .from("properties")
    .select("id, title, connect_partner_id")
    .eq("id", input.propertyId)
    .maybeSingle();

  if (error || !property) {
    console.error(
      "[CONNECT] logPartnerEngagementFromProperty property lookup failed:",
      error?.message ?? "not found",
    );
    return;
  }

  const connectPartnerId = (property.connect_partner_id as string | null) ?? null;
  if (!connectPartnerId) return;

  await logConnectPartnerActivity(supabase, {
    type: input.activityType ?? "lead_updated",
    partnerId: connectPartnerId,
    actorId: input.actorId ?? input.buyerId,
    buyerId: input.buyerId,
    propertyId: input.propertyId,
    description:
      input.description ??
      `Buyer engaged with property "${property.title ?? input.propertyId}"`,
    metadata: {
      lead_id: input.leadId ?? null,
      site_visit_id: input.siteVisitId ?? null,
    },
  });
}
